package:
  name: knossos_utils
  version: 1.0

source:
  path: ./

requirements:
  build:
    - python >=2.7,<3
    - setuptools >=20.6
    - cython >=0.23
    - h5py >=2.5
    - numpy >=1.10
    - scipy >=0.17.1
    - python-snappy >=0.5
    - gcc >=4.8

  run:
    - python >=2.7,<3
    - cython >=0.23
    - h5py >=2.5
    - numpy >=1.10
    - scipy >=0.17.1
    - python-snappy >=0.5

about:
  home: https://github.com/knossos-project/knossos_python_tools
  license: GPLv2
  license_file: LICENSE
