package:
  name: knossos_python_tools
  version: 1.0

source:
  path: ./

requirements:
  build:
    - python >=2.7,<3
    - setuptools >=20.6
    - cython >=0.24
    - h5py >=2.5
    - matplotlib >=1.5
    - numpy >=1.10
    - scipy >=0.17
    - python-snappy >=0.5
    - gcc >=4.8

  run:
    - python >=2.7,<3
    - cython >=0.24
    - h5py >=2.5
    - matplotlib >=1.5
    - numpy >=1.10
    - scipy >=0.17
    - python-snappy >=0.5
    - libgcc >=4.8  # https://github.com/ContinuumIO/anaconda-issues/issues/686

about:
  home: https://github.com/knossos-project/knossos_python_tools
  license: GPLv2
  license_file: LICENSE
